// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzRICbbSwCG7-DOvQkuNCbfMngGKgySWQ',
    appId: '1:687327317437:web:cda717ea48521503d696d4',
    messagingSenderId: '687327317437',
    projectId: 'chatapptute-c081d',
    authDomain: 'chatapptute-c081d.firebaseapp.com',
    storageBucket: 'chatapptute-c081d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGCEtXOoYYVMewizsJ7BlZ0npqVT6KKV8',
    appId: '1:687327317437:android:047959bd72bfd256d696d4',
    messagingSenderId: '687327317437',
    projectId: 'chatapptute-c081d',
    storageBucket: 'chatapptute-c081d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZOeIRIWrqtq4kNtkGtbmRGrqlfoitbPA',
    appId: '1:687327317437:ios:5f1b6e793abc21ffd696d4',
    messagingSenderId: '687327317437',
    projectId: 'chatapptute-c081d',
    storageBucket: 'chatapptute-c081d.appspot.com',
    iosClientId: '687327317437-k0sfedamqio1e79meich78jkpeldqtt3.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZOeIRIWrqtq4kNtkGtbmRGrqlfoitbPA',
    appId: '1:687327317437:ios:7f70d98e0b3feb26d696d4',
    messagingSenderId: '687327317437',
    projectId: 'chatapptute-c081d',
    storageBucket: 'chatapptute-c081d.appspot.com',
    iosClientId: '687327317437-l9i92ahgtmoh0g11scn8icst1fdg96c7.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatchat.RunnerTests',
  );
}
